# Generated by Django 3.1.5 on 2021-02-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
