# Generated by Django 3.1.5 on 2021-02-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20210210_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like_count',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.CharField(choices=[('da', 'daily'), ('me', 'memo'), ('wi', 'wish'), ('th', 'think')], default='da', max_length=2),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
